### ISSUE TITLE
Unable to run the quickstart as it failed at first run

### ISSUE THREAD

**Issue by ThomasG77** [practicajs/practica#209]
What I do?

```
mkdir demo-practica
cd demo-practica
git init . # To avoid "Command failed: npx turbo run build" due to missing .git and speedup install
npx @practica/create-node-app immediate --install-dependencies
```

It returns the following

```
❣️ Command failed: npx turbo run build
order-service:build: ERROR: command finished with error: command (services/order-service) npm run build exited (2)
command (services/order-service) npm run build exited (2)

• Packages in scope: @practica/configuration-provider, @practica/error-handling, @practica/jwt-token-verifier, @practica/logger, @practica/validation, order-service
• Running build in 6 packages
@practica/configuration-provider:build: cache miss, executing 8bc8fcc61119b8e7
@practica/validation:build: cache miss, executing 88eb730c59e11ded
@practica/jwt-token-verifier:build: cache miss, executing f3ee7b28707cce64
@practica/jwt-token-verifier:build: 
@practica/jwt-token-verifier:build: > @practica/jwt-token-verifier@0.0.1-alpha.5 build
@practica/jwt-token-verifier:build: > tsc
@practica/jwt-token-verifier:build: 
@practica/configuration-provider:build: 
@practica/configuration-provider:build: > @practica/configuration-provider@0.0.1-alpha.3 build
@practica/configuration-provider:build: > tsc
@practica/configuration-provider:build: 
@practica/validation:build: 
@practica/validation:build: > @practica/validation@0.0.1-alpha.1 build
@practica/validation:build: > tsc
@practica/validation:build: 
@practica/logger:build: cache miss, executing 910860c0ba87745c
@practica/logger:build: 
@practica/logger:build: > @practica/logger@0.0.1-alpha.4 build
@practica/logger:build: > tsc
@practica/logger:build: 
@practica/error-handling:build: cache miss, executing f45817537faf2b9a
@practica/error-handling:build: 
@practica/error-handling:build: > @practica/error-handling@0.0.2 build
@practica/error-handling:build: > tsc
@practica/error-handling:build: 
order-service:build: cache miss, executing 2e3fe06d10230f3f
order-service:build: 
order-service:build: > order-service@0.0.2 build
order-service:build: > tsc
order-service:build: 
order-service:build: domain/new-order-use-case.ts(43,3): error TS2578: Unused '@ts-expect-error' directive.
order-service:build: domain/order-schema.ts(1,8): error TS1192: Module '"/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/@practica/validation/index"' has no default export.
order-service:build: entry-points/api/server.ts(18,5): error TS2578: Unused '@ts-expect-error' directive.

 Tasks:    5 successful, 6 total
Cached:    0 cached, 6 total
  Time:    4m14.391s 
```

Then,  I do

```bash
cd services/order-service/
npm i
npm run start:dev
```

It crashs at it inherits from the issues from the first run

```
> order-service@0.0.2 start:dev
> PORT=0 PRETTY_PRINT=true nodemon start.ts

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node start.ts`
/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
entry-points/api/server.ts:18:5 - error TS2578: Unused '@ts-expect-error' directive.

18     // @ts-expect-error TODO: fix this
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/thomasg/own-projects/demo-practica/default-app-name/services/order-service/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2578 ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

PS: I'm a TypeScript noob so maybe obvious.

Update: version of Node = v16.13.0 using nvm on a Ubuntu 18.04 64 bits

**Comment by rluvaton** [comment]
Hey, thanks for opening this issue, what is your node version?

**Comment by mikicho** [comment]
@ThomasG77 Thanks for open this issue :)
What's your typescript version? (`npx tsc --version` from the `order-service` folder)

**Comment by ThomasG77** [comment]
npx tsc --version
Version 4.6.4

**Comment by rluvaton** [comment]
could you please add here the `package-lock.json` file, I'm thinking it may be related to some package version

**Comment by ThomasG77** [comment]
See https://gist.github.com/ThomasG77/dfebda550a6847a46725afb2cfdb1253

I suppose it's the `package-lock.json` from services/order-service you wanted

**Comment by mikicho** [comment]
> > What's your typescript version? (npx tsc --version from the order-service folder)
> 
> ```
> npx tsc --version
> Version 4.6.4
> ```

Interesting, it should be `Version 4.7.4`
Can you try again with this command? `npx @practica/create-node-app@0.0.4 immediate --install-dependencies`

**Comment by ThomasG77** [comment]
Same result...

**Comment by rluvaton** [comment]
which node and npm version are you running?

**Comment by rluvaton** [comment]
I think this is happening because you probably have configuration provider with earlier version

What is the content of `libraries/configuration-provider/configuration-provider.ts`?

**Comment by ThomasG77** [comment]
> which node and npm version are you running?

Answered before for node: Node = v16.13.0 using nvm on a Ubuntu 18.04 64 bits
For npm, version 8.1.0


Content of `libraries/configuration-provider/configuration-provider.ts`

```
import convict from 'convict';

// TODO: we need to change any to generic and accept the schema type from the consumer
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let convictConfigurationProvider: convict.Config<any> | undefined;

export function initialize(schema) {
  convictConfigurationProvider = convict(schema);
  convictConfigurationProvider.validate();
}

// Meant mostly for testing purposes, to allow resetting the state between tests
export function reset() {
  convictConfigurationProvider = undefined;
}

export function getValue(keyName: string): string {
  if (convictConfigurationProvider === undefined) {
    throw new Error('Configuration has not been initialized yet');
  }

  // TODO: we need to change any to generic and accept the schema type from the consumer
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  return convictConfigurationProvider.get(keyName) as string;
}
```

**Comment by goldbergyoni** [comment]
@ThomasG77 Thanks for your kind explanations and for working with us on this issue:). This might prevent similar behaviour to many others.

I have a hypothesis why this happened and released a fix: v0.0.5

I can't be 100% sure that this issue is solved but the chances are quite good

Could you please try again over a fresh folder?

Your feedback is important, highly appreciate if you can try again and let me know

While installing, please ensure that you're not pulling from the cache. You should not v0.0.5 in your package.json. If not, clean the local npm cache

**Comment by ThomasG77** [comment]
Tried 

```
npm cache clean
npx @practica/create-node-app immediate --install-dependencies
```

Same error. Due to your mention about version, I've tried to be explicit with `npx @practica/create-node-app@0.0.5 immediate --install-dependencies` and I have no error anymore. Resulting generated code mention version `"0.0.3"` in both `default-app-name/services/` and `default-app-name/services/order-service/package.json` whereas in failing case, the version was `0.0.2`.

**Comment by goldbergyoni** [comment]
So just to make sure we're on the same page - All is good now, correct?

As you're one of our first users, we'll be glad to follow your Practica adoption and provide quick help. If you wish we can also plan your desired app together using Practice principles.

**Comment by ThomasG77** [comment]
Yes, except default instructions at https://github.com/practicajs/practica#run-practicajs-from-the-command-line are not working on my machine. Other users may hit the issue.
