### ISSUE TITLE
Error while running `npx @practica/create-node-app interactive`

### ISSUE THREAD

**Issue by MatanYemini** [practicajs/practica#256]
Hi all!

**I was trying to run:** `npx @practica/create-node-app interactive`

**Chose:**
* generic-name (1)
* Fastify (2)
* Mongo (3)
* All best practices (4)

**Got:**

```
/home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Command failed: npx turbo run build --continue=false
error: The value 'false' was provided to '--continue' but it wasn't expecting any more values

Usage: turbo run --continue

For more information try '--help'


    at makeError (/home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/execa/index.js:174:9)
    at /home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDependencies (/home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/@practica/create-node-app/src/code-generator/generation-logic/generate-service.js:57:5)
    at async Object.generateApp (/home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/@practica/create-node-app/src/code-generator/generation-logic/generate-service.js:20:9)
    at async handleFlavourChoose (/home/matan/.npm/_npx/7f3b8f3562aa517a/node_modules/@practica/create-node-app/src/code-generator/entry-points/interactive-cli.js:159:9) {
  code: 1,
  stdout: '',
  stderr: "error: The value 'false' was provided to '--continue' but it wasn't expecting any more values\n" +
    '\n' +
    'Usage: turbo run --continue\n' +
    '\n' +
    "For more information try '--help'\n",
  failed: true,
  signal: null,
  cmd: 'npx turbo run build --continue=false',
  timedOut: false,
  killed: false
}
```

**Env:**

Windows 10 WSL2 (Ubuntu 20, running on it's folders)

I will add my solution if find.

Thanks

**Comment by MatanYemini** [comment]
BTW, even when just running: ` npx turbo run build --continue=false` 

I get: `error: The value 'false' was provided to '--continue' but it wasn't expecting any more values`

**Comment by MatanYemini** [comment]
Forked the repo, tried to remove the `--continue=false` to just `continue` and it worked on the forked repo. FYI

**Comment by igat64** [comment]
I have exactly the same issue
