### ISSUE TITLE
Usage: turbo.exe run --continue

### ISSUE THREAD

**Issue by ngoctiennguyen155** [practicajs/practica#257]
CLI : npx @practica/create-node-app immediate --install-dependencies
Get this error: The value 'false' was provided to '--continue' but it wasn't expecting any more values

**Comment by vsudakov** [comment]
I get the same error. Also I got this error in "interactive" mode too.

**Comment by rubek-joshi** [comment]
Windows user here and I am also facing the same issue.

**Comment by pawank121** [comment]
Got an issue on MacBook Pro M1 chip, os: Ventura 13.1

sudo npx @practica/create-node-app interactive
Password:
(node:20790) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx turbo run build --continue=false
ERROR unexpected value 'false' for '--continue' found; no more were expected

Usage: turbo run --continue

For more information, try '--help'.

    at makeError (/Users/pawankumar/.npm/_npx/20790/lib/node_modules/@practica/create-node-app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pawankumar/.npm/_npx/20790/lib/node_modules/@practica/create-node-app/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async installDependencies (/Users/pawankumar/.npm/_npx/20790/lib/node_modules/@practica/create-node-app/src/code-generator/generation-logic/generate-service.js:57:5)
    at async Object.generateApp (/Users/pawankumar/.npm/_npx/20790/lib/node_modules/@practica/create-node-app/src/code-generator/generation-logic/generate-service.js:20:9)
    at async handleFlavourChoose (/Users/pawankumar/.npm/_npx/20790/lib/node_modules/@practica/create-node-app/src/code-generator/entry-points/interactive-cli.js:159:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by augustosamame** [comment]
Msc OS Ventura 13.2.1 with M1 processor. Same error as original post.

**Comment by clabnet** [comment]
Windows 11, same problem

**Comment by AndrewAllison** [comment]
Apple M1 Max, OS: Ventura 13.2.1 

```
npx @practica/create-node-app immediate --install-dependencies

RESULTS IN:
❣️ Command failed: npx turbo run build --continue=false
ERROR unexpected value 'false' for '--continue' found; no more were expected
```

**Comment by smohadjer** [comment]
Error at the very first step for a boilerplate that boasts best practices and simplicity!
